video_reader:
  src: '../data/traffic_0.mp4'
  skip_secs: 0

show_node:
  imshow: True
  show_detection: False
  show_tracking: True
  snow_analytics: True
  show_roi: True

detection_node:
  device: 'cuda'
  model_path: '../artifacts/yolov8n.pt'

tracking_node:
  first_track_thresh: 0.5
  second_track_thresh: 0.10
  match_thresh: 0.95
  track_buffer: 256

track_manager_node:
  buffer_analytics: 0.5
  min_lifetime_track: 3
  count_cars_buffer_frames: 25
# [ 400, 105 ]
analytics_node:
  road_1: [ [ 180, 240 ], [ 233, 210 ], [ 625, 305 ], [625, 360]]